// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package db

import (
	"context"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (name, iso_code, flag, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
`

type CreateCountryParams struct {
	Name     string
	IsoCode  string
	Flag     string
	IsActive *bool
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.Name,
		arg.IsoCode,
		arg.Flag,
		arg.IsActive,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsoCode,
		&i.Flag,
		&i.IsActive,
		&i.CurrencyName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries
WHERE id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCountry, id)
	return err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
FROM countries
WHERE id = $1
`

func (q *Queries) GetCountryByID(ctx context.Context, id int64) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsoCode,
		&i.Flag,
		&i.IsActive,
		&i.CurrencyName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
FROM countries
ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsoCode,
			&i.Flag,
			&i.IsActive,
			&i.CurrencyName,
			&i.CurrencyCode,
			&i.CurrencySymbol,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET name = $2,
    iso_code = $3,
    flag = $4,
    is_active = $5
WHERE id = $1
RETURNING id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
`

type UpdateCountryParams struct {
	ID       int64
	Name     string
	IsoCode  string
	Flag     string
	IsActive *bool
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, updateCountry,
		arg.ID,
		arg.Name,
		arg.IsoCode,
		arg.Flag,
		arg.IsActive,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsoCode,
		&i.Flag,
		&i.IsActive,
		&i.CurrencyName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
