// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (
        name,
        iso_code,
        flag,
        currency_name,
        currency_code,
        currency_symbol,
        is_active
    )
VALUES ($1, $2, $3, $4, $5, $6, TRUE)
RETURNING id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
`

type CreateCountryParams struct {
	Name           string
	IsoCode        string
	Flag           string
	CurrencyName   string
	CurrencyCode   string
	CurrencySymbol string
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.Name,
		arg.IsoCode,
		arg.Flag,
		arg.CurrencyName,
		arg.CurrencyCode,
		arg.CurrencySymbol,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsoCode,
		&i.Flag,
		&i.IsActive,
		&i.CurrencyName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPaymentChannel = `-- name: CreatePaymentChannel :one
INSERT INTO payment_channels (name, channel_type, country_id)
VALUES ($1, $2, $3)
RETURNING id, name, channel_type, is_active, country_id, created_at, updated_at, deleted_at
`

type CreatePaymentChannelParams struct {
	Name        string
	ChannelType ReceivingMethods
	CountryID   int64
}

func (q *Queries) CreatePaymentChannel(ctx context.Context, arg CreatePaymentChannelParams) (PaymentChannel, error) {
	row := q.db.QueryRow(ctx, createPaymentChannel, arg.Name, arg.ChannelType, arg.CountryID)
	var i PaymentChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsActive,
		&i.CountryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
        source_country_id,
        destination_country_id,
        default_exchange_rate,
        fee,
        fee_type,
        min_transfer_amount,
        max_transfer_amount
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, source_country_id, destination_country_id, is_active, default_exchange_rate, fee, fee_type, estimated_minutes, max_transfer_amount, min_transfer_amount, created_at, updated_at, deleted_at
`

type CreateRouteParams struct {
	SourceCountryID      int64
	DestinationCountryID int64
	DefaultExchangeRate  pgtype.Numeric
	Fee                  pgtype.Numeric
	FeeType              FeeType
	MinTransferAmount    pgtype.Numeric
	MaxTransferAmount    pgtype.Numeric
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.SourceCountryID,
		arg.DestinationCountryID,
		arg.DefaultExchangeRate,
		arg.Fee,
		arg.FeeType,
		arg.MinTransferAmount,
		arg.MaxTransferAmount,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.SourceCountryID,
		&i.DestinationCountryID,
		&i.IsActive,
		&i.DefaultExchangeRate,
		&i.Fee,
		&i.FeeType,
		&i.EstimatedMinutes,
		&i.MaxTransferAmount,
		&i.MinTransferAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries
WHERE id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCountry, id)
	return err
}

const deleteRoute = `-- name: DeleteRoute :one
UPDATE routes
SET deleted_at = now(),
    is_active = FALSE,
    updated_at = now()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, source_country_id, destination_country_id, is_active, default_exchange_rate, fee, fee_type, estimated_minutes, max_transfer_amount, min_transfer_amount, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteRoute(ctx context.Context, id uuid.UUID) (Route, error) {
	row := q.db.QueryRow(ctx, deleteRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.SourceCountryID,
		&i.DestinationCountryID,
		&i.IsActive,
		&i.DefaultExchangeRate,
		&i.Fee,
		&i.FeeType,
		&i.EstimatedMinutes,
		&i.MaxTransferAmount,
		&i.MinTransferAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const doesPaymentChannelExist = `-- name: DoesPaymentChannelExist :one
SELECT id
FROM payment_channels
WHERE country_id = $1
    AND name = $2
    AND channel_type = $3
    AND is_active = TRUE
    AND deleted_at IS NULL
`

type DoesPaymentChannelExistParams struct {
	CountryID   int64
	Name        string
	ChannelType ReceivingMethods
}

func (q *Queries) DoesPaymentChannelExist(ctx context.Context, arg DoesPaymentChannelExistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, doesPaymentChannelExist, arg.CountryID, arg.Name, arg.ChannelType)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActivePCByCountryTypeAndID = `-- name: GetActivePCByCountryTypeAndID :one
SELECT pc.id, pc.name, pc.channel_type, pc.is_active, pc.country_id, pc.created_at, pc.updated_at, pc.deleted_at
FROM payment_channels pc
    JOIN countries c ON c.id = pc.country_id
WHERE pc.country_id = $1
    AND pc.channel_type = $2
    AND pc.id = $3
    AND pc.is_active = TRUE
    AND pc.deleted_at IS NULL
    AND c.is_active = TRUE
    AND c.deleted_at IS NULL
`

type GetActivePCByCountryTypeAndIDParams struct {
	CountryID   int64
	ChannelType ReceivingMethods
	ID          uuid.UUID
}

func (q *Queries) GetActivePCByCountryTypeAndID(ctx context.Context, arg GetActivePCByCountryTypeAndIDParams) (PaymentChannel, error) {
	row := q.db.QueryRow(ctx, getActivePCByCountryTypeAndID, arg.CountryID, arg.ChannelType, arg.ID)
	var i PaymentChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsActive,
		&i.CountryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActivePaymentChannelsByCountryIDs = `-- name: GetActivePaymentChannelsByCountryIDs :many
SELECT id,
    name,
    channel_type,
    country_id
FROM payment_channels
WHERE country_id = ANY($1::bigint [])
    AND is_active = TRUE
    AND deleted_at IS NULL
ORDER BY channel_type,
    name
`

type GetActivePaymentChannelsByCountryIDsRow struct {
	ID          uuid.UUID
	Name        string
	ChannelType ReceivingMethods
	CountryID   int64
}

func (q *Queries) GetActivePaymentChannelsByCountryIDs(ctx context.Context, dollar_1 []int64) ([]GetActivePaymentChannelsByCountryIDsRow, error) {
	rows, err := q.db.Query(ctx, getActivePaymentChannelsByCountryIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivePaymentChannelsByCountryIDsRow{}
	for rows.Next() {
		var i GetActivePaymentChannelsByCountryIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChannelType,
			&i.CountryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveRouteByCountries = `-- name: GetActiveRouteByCountries :one
SELECT r.id, r.source_country_id, r.destination_country_id, r.is_active, r.default_exchange_rate, r.fee, r.fee_type, r.estimated_minutes, r.max_transfer_amount, r.min_transfer_amount, r.created_at, r.updated_at, r.deleted_at
FROM routes r
    JOIN countries source ON source.id = r.source_country_id
    JOIN countries destination ON destination.id = r.destination_country_id
WHERE r.source_country_id = $1
    AND r.destination_country_id = $2
    AND r.is_active = TRUE
    AND r.deleted_at IS NULL
    AND source.is_active = TRUE
    AND source.deleted_at IS NULL
    AND destination.is_active = TRUE
    AND destination.deleted_at IS NULL
`

type GetActiveRouteByCountriesParams struct {
	SourceCountryID      int64
	DestinationCountryID int64
}

func (q *Queries) GetActiveRouteByCountries(ctx context.Context, arg GetActiveRouteByCountriesParams) (Route, error) {
	row := q.db.QueryRow(ctx, getActiveRouteByCountries, arg.SourceCountryID, arg.DestinationCountryID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.SourceCountryID,
		&i.DestinationCountryID,
		&i.IsActive,
		&i.DefaultExchangeRate,
		&i.Fee,
		&i.FeeType,
		&i.EstimatedMinutes,
		&i.MaxTransferAmount,
		&i.MinTransferAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllActiveRouteDestinations = `-- name: GetAllActiveRouteDestinations :many
SELECT r.source_country_id,
    c.id,
    c.name,
    c.iso_code,
    c.flag,
    c.currency_name,
    c.currency_code,
    c.currency_symbol,
    r.min_transfer_amount,
    r.max_transfer_amount,
    r.default_exchange_rate,
    r.fee_type,
    r.fee
FROM countries c
    JOIN routes r ON r.destination_country_id = c.id
    JOIN countries src ON src.id = r.source_country_id
WHERE r.is_active = TRUE
    AND r.deleted_at IS NULL
    AND c.is_active = TRUE
    AND c.deleted_at IS NULL
    AND src.is_active = TRUE
    AND src.deleted_at IS NULL
ORDER BY r.source_country_id,
    c.name
`

type GetAllActiveRouteDestinationsRow struct {
	SourceCountryID     int64
	ID                  int64
	Name                string
	IsoCode             string
	Flag                string
	CurrencyName        string
	CurrencyCode        string
	CurrencySymbol      string
	MinTransferAmount   pgtype.Numeric
	MaxTransferAmount   pgtype.Numeric
	DefaultExchangeRate pgtype.Numeric
	FeeType             FeeType
	Fee                 pgtype.Numeric
}

func (q *Queries) GetAllActiveRouteDestinations(ctx context.Context) ([]GetAllActiveRouteDestinationsRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveRouteDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllActiveRouteDestinationsRow{}
	for rows.Next() {
		var i GetAllActiveRouteDestinationsRow
		if err := rows.Scan(
			&i.SourceCountryID,
			&i.ID,
			&i.Name,
			&i.IsoCode,
			&i.Flag,
			&i.CurrencyName,
			&i.CurrencyCode,
			&i.CurrencySymbol,
			&i.MinTransferAmount,
			&i.MaxTransferAmount,
			&i.DefaultExchangeRate,
			&i.FeeType,
			&i.Fee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCountries = `-- name: GetAllCountries :many
SELECT id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
FROM countries
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) GetAllCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, getAllCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsoCode,
			&i.Flag,
			&i.IsActive,
			&i.CurrencyName,
			&i.CurrencyCode,
			&i.CurrencySymbol,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSourceCountries = `-- name: GetAllSourceCountries :many
SELECT DISTINCT c.id,
    c.name,
    c.iso_code,
    c.flag,
    c.currency_name,
    c.currency_code,
    c.currency_symbol
FROM countries c
    JOIN routes r ON r.source_country_id = c.id
WHERE c.is_active = TRUE
    AND c.deleted_at IS NULL
    AND r.is_active = TRUE
    AND r.deleted_at IS NULL
ORDER BY c.name
`

type GetAllSourceCountriesRow struct {
	ID             int64
	Name           string
	IsoCode        string
	Flag           string
	CurrencyName   string
	CurrencyCode   string
	CurrencySymbol string
}

func (q *Queries) GetAllSourceCountries(ctx context.Context) ([]GetAllSourceCountriesRow, error) {
	rows, err := q.db.Query(ctx, getAllSourceCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllSourceCountriesRow{}
	for rows.Next() {
		var i GetAllSourceCountriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsoCode,
			&i.Flag,
			&i.CurrencyName,
			&i.CurrencyCode,
			&i.CurrencySymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
FROM countries
WHERE id = $1
    AND is_active = TRUE
    AND deleted_at IS NULL
`

func (q *Queries) GetCountryByID(ctx context.Context, id int64) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsoCode,
		&i.Flag,
		&i.IsActive,
		&i.CurrencyName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCountryByName = `-- name: GetCountryByName :one
SELECT id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
FROM countries
WHERE name = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCountryByName(ctx context.Context, name string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByName, name)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsoCode,
		&i.Flag,
		&i.IsActive,
		&i.CurrencyName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDestCountriesBySrcCountryID = `-- name: GetDestCountriesBySrcCountryID :many
SELECT c.id,
    c.name,
    c.iso_code,
    c.flag,
    c.currency_name,
    c.currency_code,
    c.currency_symbol,
    r.min_transfer_amount,
    r.max_transfer_amount,
    r.default_exchange_rate,
    r.fee_type,
    r.fee
FROM countries c
    JOIN routes r ON r.destination_country_id = c.id
    JOIN countries src ON src.id = r.source_country_id
WHERE r.source_country_id = $1
    AND r.is_active = TRUE
    AND r.deleted_at IS NULL
    AND c.is_active = TRUE
    AND c.deleted_at IS NULL
    AND src.is_active = TRUE
    AND src.deleted_at IS NULL
ORDER BY c.name
`

type GetDestCountriesBySrcCountryIDRow struct {
	ID                  int64
	Name                string
	IsoCode             string
	Flag                string
	CurrencyName        string
	CurrencyCode        string
	CurrencySymbol      string
	MinTransferAmount   pgtype.Numeric
	MaxTransferAmount   pgtype.Numeric
	DefaultExchangeRate pgtype.Numeric
	FeeType             FeeType
	Fee                 pgtype.Numeric
}

func (q *Queries) GetDestCountriesBySrcCountryID(ctx context.Context, sourceCountryID int64) ([]GetDestCountriesBySrcCountryIDRow, error) {
	rows, err := q.db.Query(ctx, getDestCountriesBySrcCountryID, sourceCountryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDestCountriesBySrcCountryIDRow{}
	for rows.Next() {
		var i GetDestCountriesBySrcCountryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsoCode,
			&i.Flag,
			&i.CurrencyName,
			&i.CurrencyCode,
			&i.CurrencySymbol,
			&i.MinTransferAmount,
			&i.MaxTransferAmount,
			&i.DefaultExchangeRate,
			&i.FeeType,
			&i.Fee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentChannelByCountryID = `-- name: GetPaymentChannelByCountryID :one
SELECT id, name, channel_type, is_active, country_id, created_at, updated_at, deleted_at
FROM payment_channels
WHERE country_id = $1
`

func (q *Queries) GetPaymentChannelByCountryID(ctx context.Context, countryID int64) (PaymentChannel, error) {
	row := q.db.QueryRow(ctx, getPaymentChannelByCountryID, countryID)
	var i PaymentChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsActive,
		&i.CountryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentChannelByID = `-- name: GetPaymentChannelByID :one
SELECT id, name, channel_type, is_active, country_id, created_at, updated_at, deleted_at
FROM payment_channels
WHERE id = $1
`

func (q *Queries) GetPaymentChannelByID(ctx context.Context, id uuid.UUID) (PaymentChannel, error) {
	row := q.db.QueryRow(ctx, getPaymentChannelByID, id)
	var i PaymentChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsActive,
		&i.CountryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, source_country_id, destination_country_id, is_active, default_exchange_rate, fee, fee_type, estimated_minutes, max_transfer_amount, min_transfer_amount, created_at, updated_at, deleted_at
FROM routes
WHERE deleted_at IS NULL
    AND source_country_id = COALESCE(NULLIF($1::bigint, 0), source_country_id)
    AND destination_country_id = COALESCE(NULLIF($2::bigint, 0), destination_country_id)
    AND is_active = COALESCE(NULLIF($3::text, '')::boolean, is_active)
ORDER BY created_at DESC
`

type ListRoutesParams struct {
	SourceCountryID      int64
	DestinationCountryID int64
	IsActive             string
}

func (q *Queries) ListRoutes(ctx context.Context, arg ListRoutesParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutes, arg.SourceCountryID, arg.DestinationCountryID, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.SourceCountryID,
			&i.DestinationCountryID,
			&i.IsActive,
			&i.DefaultExchangeRate,
			&i.Fee,
			&i.FeeType,
			&i.EstimatedMinutes,
			&i.MaxTransferAmount,
			&i.MinTransferAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRouteActive = `-- name: ToggleRouteActive :one
UPDATE routes
SET is_active = NOT is_active,
    updated_at = now()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, source_country_id, destination_country_id, is_active, default_exchange_rate, fee, fee_type, estimated_minutes, max_transfer_amount, min_transfer_amount, created_at, updated_at, deleted_at
`

func (q *Queries) ToggleRouteActive(ctx context.Context, id uuid.UUID) (Route, error) {
	row := q.db.QueryRow(ctx, toggleRouteActive, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.SourceCountryID,
		&i.DestinationCountryID,
		&i.IsActive,
		&i.DefaultExchangeRate,
		&i.Fee,
		&i.FeeType,
		&i.EstimatedMinutes,
		&i.MaxTransferAmount,
		&i.MinTransferAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET name = $2,
    iso_code = $3,
    flag = $4,
    currency_name = $5,
    currency_code = $6,
    currency_symbol = $7,
    is_active = $8
WHERE id = $1
RETURNING id, name, iso_code, flag, is_active, currency_name, currency_code, currency_symbol, created_at, updated_at, deleted_at
`

type UpdateCountryParams struct {
	ID             int64
	Name           string
	IsoCode        string
	Flag           string
	CurrencyName   string
	CurrencyCode   string
	CurrencySymbol string
	IsActive       bool
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, updateCountry,
		arg.ID,
		arg.Name,
		arg.IsoCode,
		arg.Flag,
		arg.CurrencyName,
		arg.CurrencyCode,
		arg.CurrencySymbol,
		arg.IsActive,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsoCode,
		&i.Flag,
		&i.IsActive,
		&i.CurrencyName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes
SET default_exchange_rate = $2,
    fee = $3,
    fee_type = $4,
    min_transfer_amount = $5,
    max_transfer_amount = $6,
    updated_at = now()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, source_country_id, destination_country_id, is_active, default_exchange_rate, fee, fee_type, estimated_minutes, max_transfer_amount, min_transfer_amount, created_at, updated_at, deleted_at
`

type UpdateRouteParams struct {
	ID                  uuid.UUID
	DefaultExchangeRate pgtype.Numeric
	Fee                 pgtype.Numeric
	FeeType             FeeType
	MinTransferAmount   pgtype.Numeric
	MaxTransferAmount   pgtype.Numeric
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.ID,
		arg.DefaultExchangeRate,
		arg.Fee,
		arg.FeeType,
		arg.MinTransferAmount,
		arg.MaxTransferAmount,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.SourceCountryID,
		&i.DestinationCountryID,
		&i.IsActive,
		&i.DefaultExchangeRate,
		&i.Fee,
		&i.FeeType,
		&i.EstimatedMinutes,
		&i.MaxTransferAmount,
		&i.MinTransferAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
