// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardActionRequiredCounts = `-- name: DashboardActionRequiredCounts :one
SELECT COUNT(*) FILTER (
        WHERE t.status IN ('PAYMENT_RECEIVED', 'VERIFYING')
    )::bigint AS payment_verification_count,
    COUNT(*) FILTER (
        WHERE t.status = 'PROCESSING'
    )::bigint AS processing_count,
    COUNT(*) FILTER (
        WHERE t.status = 'PENDING_PAYMENT'
            AND t.expires_at <= $1::timestamptz
    )::bigint AS expiring_count
FROM transfers t
WHERE t.deleted_at IS NULL
`

type DashboardActionRequiredCountsRow struct {
	PaymentVerificationCount int64
	ProcessingCount          int64
	ExpiringCount            int64
}

func (q *Queries) DashboardActionRequiredCounts(ctx context.Context, expiringBefore time.Time) (DashboardActionRequiredCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardActionRequiredCounts, expiringBefore)
	var i DashboardActionRequiredCountsRow
	err := row.Scan(&i.PaymentVerificationCount, &i.ProcessingCount, &i.ExpiringCount)
	return i, err
}

const dashboardActionRequiredTransfers = `-- name: DashboardActionRequiredTransfers :many
SELECT t.id,
    t.reference,
    t.status,
    t.amount_sent,
    t.sender_phone,
    t.receiving_account_name,
    t.receiving_method,
    t.expires_at,
    t.created_at,
    src.name AS source_country_name,
    src.currency_code AS source_currency_code,
    src.currency_symbol AS source_currency_symbol,
    dst.name AS destination_country_name,
    dst.currency_code AS destination_currency_code
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
    JOIN countries dst ON dst.id = r.destination_country_id
WHERE t.deleted_at IS NULL
    AND (
        t.status IN (
            'PAYMENT_RECEIVED',
            'VERIFYING',
            'PROCESSING'
        )
        OR (
            t.status = 'PENDING_PAYMENT'
            AND t.expires_at <= $1::timestamptz
        )
    )
ORDER BY t.created_at DESC
LIMIT $2
`

type DashboardActionRequiredTransfersParams struct {
	ExpiringBefore time.Time
	RowLimit       int32
}

type DashboardActionRequiredTransfersRow struct {
	ID                      uuid.UUID
	Reference               string
	Status                  TransferStatus
	AmountSent              pgtype.Numeric
	SenderPhone             string
	ReceivingAccountName    string
	ReceivingMethod         ReceivingMethods
	ExpiresAt               time.Time
	CreatedAt               time.Time
	SourceCountryName       string
	SourceCurrencyCode      string
	SourceCurrencySymbol    string
	DestinationCountryName  string
	DestinationCurrencyCode string
}

func (q *Queries) DashboardActionRequiredTransfers(ctx context.Context, arg DashboardActionRequiredTransfersParams) ([]DashboardActionRequiredTransfersRow, error) {
	rows, err := q.db.Query(ctx, dashboardActionRequiredTransfers, arg.ExpiringBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardActionRequiredTransfersRow{}
	for rows.Next() {
		var i DashboardActionRequiredTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Status,
			&i.AmountSent,
			&i.SenderPhone,
			&i.ReceivingAccountName,
			&i.ReceivingMethod,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.SourceCountryName,
			&i.SourceCurrencyCode,
			&i.SourceCurrencySymbol,
			&i.DestinationCountryName,
			&i.DestinationCurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardDailyVolume = `-- name: DashboardDailyVolume :many
SELECT (DATE_TRUNC('day', t.created_at AT TIME ZONE 'UTC'))::date AS day,
    src.currency_code AS currency_code,
    COUNT(*)::bigint AS transfer_count,
    COALESCE(SUM(t.amount_sent), 0)::numeric AS volume
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
WHERE t.deleted_at IS NULL
    AND t.created_at >= $1::timestamptz
    AND t.created_at < $2::timestamptz
GROUP BY day,
    src.currency_code
ORDER BY day,
    src.currency_code
`

type DashboardDailyVolumeParams struct {
	FromTs time.Time
	ToTs   time.Time
}

type DashboardDailyVolumeRow struct {
	Day           pgtype.Date
	CurrencyCode  string
	TransferCount int64
	Volume        pgtype.Numeric
}

func (q *Queries) DashboardDailyVolume(ctx context.Context, arg DashboardDailyVolumeParams) ([]DashboardDailyVolumeRow, error) {
	rows, err := q.db.Query(ctx, dashboardDailyVolume, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardDailyVolumeRow{}
	for rows.Next() {
		var i DashboardDailyVolumeRow
		if err := rows.Scan(
			&i.Day,
			&i.CurrencyCode,
			&i.TransferCount,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardMoneyTotals = `-- name: DashboardMoneyTotals :many
SELECT src.currency_code AS source_currency_code,
    dst.currency_code AS destination_currency_code,
    COUNT(*)::bigint AS transfer_count,
    COALESCE(SUM(t.amount_sent), 0)::numeric AS total_amount_sent,
    COALESCE(SUM(t.fee), 0)::numeric AS total_fees
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
    JOIN countries dst ON dst.id = r.destination_country_id
WHERE t.deleted_at IS NULL
    AND t.created_at >= $1::timestamptz
    AND t.created_at < $2::timestamptz
GROUP BY src.currency_code,
    dst.currency_code
ORDER BY src.currency_code,
    dst.currency_code
`

type DashboardMoneyTotalsParams struct {
	FromTs time.Time
	ToTs   time.Time
}

type DashboardMoneyTotalsRow struct {
	SourceCurrencyCode      string
	DestinationCurrencyCode string
	TransferCount           int64
	TotalAmountSent         pgtype.Numeric
	TotalFees               pgtype.Numeric
}

func (q *Queries) DashboardMoneyTotals(ctx context.Context, arg DashboardMoneyTotalsParams) ([]DashboardMoneyTotalsRow, error) {
	rows, err := q.db.Query(ctx, dashboardMoneyTotals, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardMoneyTotalsRow{}
	for rows.Next() {
		var i DashboardMoneyTotalsRow
		if err := rows.Scan(
			&i.SourceCurrencyCode,
			&i.DestinationCurrencyCode,
			&i.TransferCount,
			&i.TotalAmountSent,
			&i.TotalFees,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentActivity = `-- name: DashboardRecentActivity :many
SELECT e.id,
    e.status,
    e.actor,
    e.note,
    e.created_at,
    t.reference
FROM transfer_events e
    JOIN transfers t ON t.id = e.transfer_id
WHERE t.deleted_at IS NULL
ORDER BY e.created_at DESC
LIMIT $1
`

type DashboardRecentActivityRow struct {
	ID        uuid.UUID
	Status    TransferStatus
	Actor     string
	Note      *string
	CreatedAt time.Time
	Reference string
}

func (q *Queries) DashboardRecentActivity(ctx context.Context, rowLimit int32) ([]DashboardRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentActivity, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentActivityRow{}
	for rows.Next() {
		var i DashboardRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Actor,
			&i.Note,
			&i.CreatedAt,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentTransfers = `-- name: DashboardRecentTransfers :many
SELECT t.id,
    t.reference,
    t.status,
    t.amount_sent,
    t.sender_phone,
    t.receiving_account_name,
    t.receiving_method,
    t.created_at,
    src.name AS source_country_name,
    src.currency_code AS source_currency_code,
    src.currency_symbol AS source_currency_symbol,
    dst.name AS destination_country_name,
    dst.currency_code AS destination_currency_code
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
    JOIN countries dst ON dst.id = r.destination_country_id
WHERE t.deleted_at IS NULL
    AND t.created_at >= $1::timestamptz
    AND t.created_at < $2::timestamptz
ORDER BY t.created_at DESC
LIMIT $3
`

type DashboardRecentTransfersParams struct {
	FromTs   time.Time
	ToTs     time.Time
	RowLimit int32
}

type DashboardRecentTransfersRow struct {
	ID                      uuid.UUID
	Reference               string
	Status                  TransferStatus
	AmountSent              pgtype.Numeric
	SenderPhone             string
	ReceivingAccountName    string
	ReceivingMethod         ReceivingMethods
	CreatedAt               time.Time
	SourceCountryName       string
	SourceCurrencyCode      string
	SourceCurrencySymbol    string
	DestinationCountryName  string
	DestinationCurrencyCode string
}

func (q *Queries) DashboardRecentTransfers(ctx context.Context, arg DashboardRecentTransfersParams) ([]DashboardRecentTransfersRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentTransfers, arg.FromTs, arg.ToTs, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentTransfersRow{}
	for rows.Next() {
		var i DashboardRecentTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Status,
			&i.AmountSent,
			&i.SenderPhone,
			&i.ReceivingAccountName,
			&i.ReceivingMethod,
			&i.CreatedAt,
			&i.SourceCountryName,
			&i.SourceCurrencyCode,
			&i.SourceCurrencySymbol,
			&i.DestinationCountryName,
			&i.DestinationCurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardStatusCounts = `-- name: DashboardStatusCounts :many
SELECT t.status,
    COUNT(*)::bigint AS count
FROM transfers t
WHERE t.deleted_at IS NULL
    AND t.created_at >= $1::timestamptz
    AND t.created_at < $2::timestamptz
GROUP BY t.status
ORDER BY t.status
`

type DashboardStatusCountsParams struct {
	FromTs time.Time
	ToTs   time.Time
}

type DashboardStatusCountsRow struct {
	Status TransferStatus
	Count  int64
}

func (q *Queries) DashboardStatusCounts(ctx context.Context, arg DashboardStatusCountsParams) ([]DashboardStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, dashboardStatusCounts, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardStatusCountsRow{}
	for rows.Next() {
		var i DashboardStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTopRoutes = `-- name: DashboardTopRoutes :many
SELECT r.id AS route_id,
    src.id AS source_country_id,
    src.name AS source_country_name,
    src.iso_code AS source_iso_code,
    src.flag AS source_flag,
    src.currency_code AS source_currency_code,
    dst.id AS destination_country_id,
    dst.name AS destination_country_name,
    dst.iso_code AS destination_iso_code,
    dst.flag AS destination_flag,
    dst.currency_code AS destination_currency_code,
    COUNT(*)::bigint AS transfer_count,
    COALESCE(SUM(t.amount_sent), 0)::numeric AS transfer_volume
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
    JOIN countries dst ON dst.id = r.destination_country_id
WHERE t.deleted_at IS NULL
    AND t.created_at >= $1::timestamptz
    AND t.created_at < $2::timestamptz
GROUP BY r.id,
    src.id,
    src.name,
    src.iso_code,
    src.flag,
    src.currency_code,
    dst.id,
    dst.name,
    dst.iso_code,
    dst.flag,
    dst.currency_code
ORDER BY transfer_count DESC,
    transfer_volume DESC
LIMIT $3
`

type DashboardTopRoutesParams struct {
	FromTs   time.Time
	ToTs     time.Time
	RowLimit int32
}

type DashboardTopRoutesRow struct {
	RouteID                 uuid.UUID
	SourceCountryID         int64
	SourceCountryName       string
	SourceIsoCode           string
	SourceFlag              string
	SourceCurrencyCode      string
	DestinationCountryID    int64
	DestinationCountryName  string
	DestinationIsoCode      string
	DestinationFlag         string
	DestinationCurrencyCode string
	TransferCount           int64
	TransferVolume          pgtype.Numeric
}

// Ranked by transfer_count (most-used corridors in the period).
func (q *Queries) DashboardTopRoutes(ctx context.Context, arg DashboardTopRoutesParams) ([]DashboardTopRoutesRow, error) {
	rows, err := q.db.Query(ctx, dashboardTopRoutes, arg.FromTs, arg.ToTs, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardTopRoutesRow{}
	for rows.Next() {
		var i DashboardTopRoutesRow
		if err := rows.Scan(
			&i.RouteID,
			&i.SourceCountryID,
			&i.SourceCountryName,
			&i.SourceIsoCode,
			&i.SourceFlag,
			&i.SourceCurrencyCode,
			&i.DestinationCountryID,
			&i.DestinationCountryName,
			&i.DestinationIsoCode,
			&i.DestinationFlag,
			&i.DestinationCurrencyCode,
			&i.TransferCount,
			&i.TransferVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
