// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status = 'completed',
    response_code = $3,
    response_body = $4,
    transfer_id = $5
WHERE actor_id = $1
  AND key = $2
`

type CompleteIdempotencyKeyParams struct {
	ActorID      string
	Key          string
	ResponseCode *int32
	ResponseBody []byte
	TransferID   pgtype.UUID
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ActorID,
		arg.Key,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.TransferID,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, key, actor_id, request_hash, status, response_code, response_body, transfer_id, created_at, expires_at
FROM idempotency_keys
WHERE actor_id = $1
  AND key = $2
  AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	ActorID string
	Key     string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ActorID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ActorID,
		&i.RequestHash,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.TransferID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (key, actor_id, request_hash, status, expires_at)
VALUES ($1, $2, $3, 'processing', $4)
ON CONFLICT (actor_id, key) DO NOTHING
RETURNING id, key, actor_id, request_hash, status, response_code, response_body, transfer_id, created_at, expires_at
`

type InsertIdempotencyKeyParams struct {
	Key         string
	ActorID     string
	RequestHash string
	ExpiresAt   time.Time
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.Key,
		arg.ActorID,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ActorID,
		&i.RequestHash,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.TransferID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
