// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FeeType string

const (
	FeeTypeFixed      FeeType = "fixed"
	FeeTypePercentage FeeType = "percentage"
)

func (e *FeeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeeType(s)
	case string:
		*e = FeeType(s)
	default:
		return fmt.Errorf("unsupported scan type for FeeType: %T", src)
	}
	return nil
}

type NullFeeType struct {
	FeeType FeeType
	Valid   bool // Valid is true if FeeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeeType) Scan(value interface{}) error {
	if value == nil {
		ns.FeeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeeType), nil
}

type ReceivingMethods string

const (
	ReceivingMethodsBANK        ReceivingMethods = "BANK"
	ReceivingMethodsMOBILEMONEY ReceivingMethods = "MOBILE_MONEY"
)

func (e *ReceivingMethods) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReceivingMethods(s)
	case string:
		*e = ReceivingMethods(s)
	default:
		return fmt.Errorf("unsupported scan type for ReceivingMethods: %T", src)
	}
	return nil
}

type NullReceivingMethods struct {
	ReceivingMethods ReceivingMethods
	Valid            bool // Valid is true if ReceivingMethods is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReceivingMethods) Scan(value interface{}) error {
	if value == nil {
		ns.ReceivingMethods, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReceivingMethods.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReceivingMethods) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReceivingMethods), nil
}

type TransferStatus string

const (
	TransferStatusPENDINGPAYMENT  TransferStatus = "PENDING_PAYMENT"
	TransferStatusPAYMENTRECEIVED TransferStatus = "PAYMENT_RECEIVED"
	TransferStatusVERIFYING       TransferStatus = "VERIFYING"
	TransferStatusPROCESSING      TransferStatus = "PROCESSING"
	TransferStatusCOMPLETED       TransferStatus = "COMPLETED"
	TransferStatusFAILED          TransferStatus = "FAILED"
	TransferStatusCANCELLED       TransferStatus = "CANCELLED"
)

func (e *TransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferStatus(s)
	case string:
		*e = TransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferStatus: %T", src)
	}
	return nil
}

type NullTransferStatus struct {
	TransferStatus TransferStatus
	Valid          bool // Valid is true if TransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Country struct {
	ID             int64
	Name           string
	IsoCode        string
	Flag           string
	IsActive       bool
	CurrencyName   string
	CurrencyCode   string
	CurrencySymbol string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type IdempotencyKey struct {
	ID           uuid.UUID
	Key          string
	ActorID      string
	RequestHash  string
	Status       string
	ResponseCode *int32
	ResponseBody []byte
	TransferID   pgtype.UUID
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type PaymentChannel struct {
	ID          uuid.UUID
	Name        string
	ChannelType ReceivingMethods
	IsActive    bool
	CountryID   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type Route struct {
	ID                   uuid.UUID
	SourceCountryID      int64
	DestinationCountryID int64
	IsActive             bool
	DefaultExchangeRate  pgtype.Numeric
	Fee                  pgtype.Numeric
	FeeType              FeeType
	EstimatedMinutes     *int32
	MaxTransferAmount    pgtype.Numeric
	MinTransferAmount    pgtype.Numeric
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            pgtype.Timestamptz
}

type Transfer struct {
	ID                         uuid.UUID
	Reference                  string
	RouteID                    uuid.UUID
	Status                     TransferStatus
	SenderPhone                string
	ReceivingAccountName       string
	ReceivingMobileMoneyNumber *string
	ReceivingMethod            ReceivingMethods
	ReceivingMoneyNetworkID    pgtype.UUID
	ReceivingBankID            pgtype.UUID
	ReceivingBankAccount       *string
	PaymentProofKey            *string
	ExchangeRate               pgtype.Numeric
	Fee                        pgtype.Numeric
	AmountSent                 pgtype.Numeric
	AmountReceived             pgtype.Numeric
	Notes                      *string
	ExpiresAt                  time.Time
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  pgtype.Timestamptz
}

type TransferEvent struct {
	ID         uuid.UUID
	TransferID uuid.UUID
	Status     TransferStatus
	Actor      string
	Note       *string
	CreatedAt  time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Role         UserRole
}
