// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FeeType string

const (
	FeeTypeFixed      FeeType = "fixed"
	FeeTypePercentage FeeType = "percentage"
)

func (e *FeeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeeType(s)
	case string:
		*e = FeeType(s)
	default:
		return fmt.Errorf("unsupported scan type for FeeType: %T", src)
	}
	return nil
}

type NullFeeType struct {
	FeeType FeeType
	Valid   bool // Valid is true if FeeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeeType) Scan(value interface{}) error {
	if value == nil {
		ns.FeeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeeType), nil
}

type ReceivingMethod string

const (
	ReceivingMethodBANK        ReceivingMethod = "BANK"
	ReceivingMethodMOBILEMONEY ReceivingMethod = "MOBILE_MONEY"
)

func (e *ReceivingMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReceivingMethod(s)
	case string:
		*e = ReceivingMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for ReceivingMethod: %T", src)
	}
	return nil
}

type NullReceivingMethod struct {
	ReceivingMethod ReceivingMethod
	Valid           bool // Valid is true if ReceivingMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReceivingMethod) Scan(value interface{}) error {
	if value == nil {
		ns.ReceivingMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReceivingMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReceivingMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReceivingMethod), nil
}

type TransferStatus string

const (
	TransferStatusPENDINGPAYMENT  TransferStatus = "PENDING_PAYMENT"
	TransferStatusPAYMENTRECEIVED TransferStatus = "PAYMENT_RECEIVED"
	TransferStatusVERIFYING       TransferStatus = "VERIFYING"
	TransferStatusPROCESSING      TransferStatus = "PROCESSING"
	TransferStatusCOMPLETED       TransferStatus = "COMPLETED"
	TransferStatusFAILED          TransferStatus = "FAILED"
	TransferStatusCANCELLED       TransferStatus = "CANCELLED"
)

func (e *TransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferStatus(s)
	case string:
		*e = TransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferStatus: %T", src)
	}
	return nil
}

type NullTransferStatus struct {
	TransferStatus TransferStatus
	Valid          bool // Valid is true if TransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferStatus), nil
}

type Country struct {
	ID             int64
	Name           string
	IsoCode        string
	Flag           string
	IsActive       *bool
	CurrencyName   string
	CurrencyCode   string
	CurrencySymbol string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type Route struct {
	ID                   uuid.UUID
	SourceCountryID      int64
	DestinationCountryID int64
	IsActive             bool
	DefaultExchangeRate  pgtype.Numeric
	Fee                  pgtype.Numeric
	FeeType              FeeType
	EstimatedMinutes     *int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            pgtype.Timestamptz
}

type Transfer struct {
	ID                  uuid.UUID
	Reference           string
	RouteID             uuid.UUID
	Status              TransferStatus
	SenderName          string
	SenderPhone         string
	RecipientName       string
	RecipientPhone      string
	ReceivingMethod     ReceivingMethod
	NetworkName         string
	BankName            *string
	RecipientAccount    string
	SendAmount          pgtype.Numeric
	ReceiveAmount       pgtype.Numeric
	SourceCurrency      string
	DestinationCurrency string
	ExchangeRate        pgtype.Numeric
	Fee                 pgtype.Numeric
	PaymentChannel      string
	PaymentProofKey     *string
	Notes               *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           pgtype.Timestamptz
}
