// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentAccount = `-- name: CreatePaymentAccount :one
INSERT INTO payment_accounts (
        country_id,
        payment_method,
        name,
        account_name,
        account_number,
        phone_number,
        sort_code,
        iban,
        payment_channel_id,
        currency_code
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, country_id, payment_method, name, account_name, account_number, payment_channel_id, currency_code, is_active, created_at, updated_at, deleted_at, phone_number, sort_code, iban
`

type CreatePaymentAccountParams struct {
	CountryID        int64
	PaymentMethod    ReceivingMethods
	Name             string
	AccountName      string
	AccountNumber    *string
	PhoneNumber      *string
	SortCode         *string
	Iban             *string
	PaymentChannelID pgtype.UUID
	CurrencyCode     string
}

func (q *Queries) CreatePaymentAccount(ctx context.Context, arg CreatePaymentAccountParams) (PaymentAccount, error) {
	row := q.db.QueryRow(ctx, createPaymentAccount,
		arg.CountryID,
		arg.PaymentMethod,
		arg.Name,
		arg.AccountName,
		arg.AccountNumber,
		arg.PhoneNumber,
		arg.SortCode,
		arg.Iban,
		arg.PaymentChannelID,
		arg.CurrencyCode,
	)
	var i PaymentAccount
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.PaymentMethod,
		&i.Name,
		&i.AccountName,
		&i.AccountNumber,
		&i.PaymentChannelID,
		&i.CurrencyCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PhoneNumber,
		&i.SortCode,
		&i.Iban,
	)
	return i, err
}

const listActivePaymentAccountsByCountryID = `-- name: ListActivePaymentAccountsByCountryID :many
SELECT pa.id,
    pa.country_id,
    pa.payment_method,
    pa.name,
    pa.account_name,
    pa.account_number,
    pa.phone_number,
    pa.sort_code,
    pa.iban,
    pa.currency_code,
    pc.name AS channel_name
FROM payment_accounts pa
    LEFT JOIN payment_channels pc ON pc.id = pa.payment_channel_id
    AND pc.deleted_at IS NULL
WHERE pa.country_id = $1
    AND pa.is_active = TRUE
    AND pa.deleted_at IS NULL
ORDER BY pa.payment_method,
    pa.name
`

type ListActivePaymentAccountsByCountryIDRow struct {
	ID            uuid.UUID
	CountryID     int64
	PaymentMethod ReceivingMethods
	Name          string
	AccountName   string
	AccountNumber *string
	PhoneNumber   *string
	SortCode      *string
	Iban          *string
	CurrencyCode  string
	ChannelName   *string
}

func (q *Queries) ListActivePaymentAccountsByCountryID(ctx context.Context, countryID int64) ([]ListActivePaymentAccountsByCountryIDRow, error) {
	rows, err := q.db.Query(ctx, listActivePaymentAccountsByCountryID, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePaymentAccountsByCountryIDRow{}
	for rows.Next() {
		var i ListActivePaymentAccountsByCountryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.PaymentMethod,
			&i.Name,
			&i.AccountName,
			&i.AccountNumber,
			&i.PhoneNumber,
			&i.SortCode,
			&i.Iban,
			&i.CurrencyCode,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
