// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promo_codes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRedemptionsByPromoCodeAndSender = `-- name: CountRedemptionsByPromoCodeAndSender :one
SELECT COUNT(*)::bigint
FROM promo_code_redemptions
WHERE promo_code_id = $1
    AND sender_phone = $2
`

type CountRedemptionsByPromoCodeAndSenderParams struct {
	PromoCodeID uuid.UUID
	SenderPhone string
}

func (q *Queries) CountRedemptionsByPromoCodeAndSender(ctx context.Context, arg CountRedemptionsByPromoCodeAndSenderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRedemptionsByPromoCodeAndSender, arg.PromoCodeID, arg.SenderPhone)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRedemptionsByPromoCodeID = `-- name: CountRedemptionsByPromoCodeID :one
SELECT COUNT(*)::bigint
FROM promo_code_redemptions
WHERE promo_code_id = $1
`

func (q *Queries) CountRedemptionsByPromoCodeID(ctx context.Context, promoCodeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRedemptionsByPromoCodeID, promoCodeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes (
        code,
        discount_percentage,
        start_date,
        end_date,
        max_uses,
        max_uses_per_user
    )
VALUES (
        UPPER(trim($1)),
        $2,
        $3,
        $4,
        $5,
        $6
    )
RETURNING id, code, discount_percentage, start_date, end_date, max_uses, max_uses_per_user, created_at, updated_at, deleted_at
`

type CreatePromoCodeParams struct {
	Code               string
	DiscountPercentage pgtype.Numeric
	StartDate          time.Time
	EndDate            time.Time
	MaxUses            int32
	MaxUsesPerUser     int32
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, createPromoCode,
		arg.Code,
		arg.DiscountPercentage,
		arg.StartDate,
		arg.EndDate,
		arg.MaxUses,
		arg.MaxUsesPerUser,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercentage,
		&i.StartDate,
		&i.EndDate,
		&i.MaxUses,
		&i.MaxUsesPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePromoCode = `-- name: DeletePromoCode :one
UPDATE promo_codes
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, code, discount_percentage, start_date, end_date, max_uses, max_uses_per_user, created_at, updated_at, deleted_at
`

func (q *Queries) DeletePromoCode(ctx context.Context, id uuid.UUID) (PromoCode, error) {
	row := q.db.QueryRow(ctx, deletePromoCode, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercentage,
		&i.StartDate,
		&i.EndDate,
		&i.MaxUses,
		&i.MaxUsesPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllPromoCodes = `-- name: GetAllPromoCodes :many
SELECT id, code, discount_percentage, start_date, end_date, max_uses, max_uses_per_user, created_at, updated_at, deleted_at
FROM promo_codes
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllPromoCodes(ctx context.Context) ([]PromoCode, error) {
	rows, err := q.db.Query(ctx, getAllPromoCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoCode{}
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DiscountPercentage,
			&i.StartDate,
			&i.EndDate,
			&i.MaxUses,
			&i.MaxUsesPerUser,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT id, code, discount_percentage, start_date, end_date, max_uses, max_uses_per_user, created_at, updated_at, deleted_at
FROM promo_codes
WHERE code = UPPER(trim($1))
    AND deleted_at IS NULL
`

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByCode, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercentage,
		&i.StartDate,
		&i.EndDate,
		&i.MaxUses,
		&i.MaxUsesPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPromoCodeByCodeForUpdate = `-- name: GetPromoCodeByCodeForUpdate :one
SELECT id, code, discount_percentage, start_date, end_date, max_uses, max_uses_per_user, created_at, updated_at, deleted_at
FROM promo_codes
WHERE code = UPPER(trim($1))
    AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetPromoCodeByCodeForUpdate(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByCodeForUpdate, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercentage,
		&i.StartDate,
		&i.EndDate,
		&i.MaxUses,
		&i.MaxUsesPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPromoCodeByID = `-- name: GetPromoCodeByID :one
SELECT id, code, discount_percentage, start_date, end_date, max_uses, max_uses_per_user, created_at, updated_at, deleted_at
FROM promo_codes
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetPromoCodeByID(ctx context.Context, id uuid.UUID) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByID, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercentage,
		&i.StartDate,
		&i.EndDate,
		&i.MaxUses,
		&i.MaxUsesPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const redeemPromoCode = `-- name: RedeemPromoCode :one
INSERT INTO promo_code_redemptions (
        promo_code_id,
        transfer_id,
        sender_phone,
        discount_percentage
    )
VALUES ($1, $2, $3, $4)
RETURNING id
`

type RedeemPromoCodeParams struct {
	PromoCodeID        uuid.UUID
	TransferID         uuid.UUID
	SenderPhone        string
	DiscountPercentage pgtype.Numeric
}

func (q *Queries) RedeemPromoCode(ctx context.Context, arg RedeemPromoCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, redeemPromoCode,
		arg.PromoCodeID,
		arg.TransferID,
		arg.SenderPhone,
		arg.DiscountPercentage,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updatePromoCode = `-- name: UpdatePromoCode :one
UPDATE promo_codes
SET discount_percentage = $2,
    start_date = $3,
    end_date = $4,
    max_uses = $5,
    max_uses_per_user = $6,
    updated_at = now()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, code, discount_percentage, start_date, end_date, max_uses, max_uses_per_user, created_at, updated_at, deleted_at
`

type UpdatePromoCodeParams struct {
	ID                 uuid.UUID
	DiscountPercentage pgtype.Numeric
	StartDate          time.Time
	EndDate            time.Time
	MaxUses            int32
	MaxUsesPerUser     int32
}

func (q *Queries) UpdatePromoCode(ctx context.Context, arg UpdatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, updatePromoCode,
		arg.ID,
		arg.DiscountPercentage,
		arg.StartDate,
		arg.EndDate,
		arg.MaxUses,
		arg.MaxUsesPerUser,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercentage,
		&i.StartDate,
		&i.EndDate,
		&i.MaxUses,
		&i.MaxUsesPerUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
