// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	CreatePaymentChannel(ctx context.Context, arg CreatePaymentChannelParams) (PaymentChannel, error)
	CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (uuid.UUID, error)
	CreateTransferEvent(ctx context.Context, arg CreateTransferEventParams) (TransferEvent, error)
	DeleteCountry(ctx context.Context, id int64) error
	DeleteRoute(ctx context.Context, id uuid.UUID) (Route, error)
	DoesPaymentChannelExist(ctx context.Context, arg DoesPaymentChannelExistParams) (uuid.UUID, error)
	GetActivePCByCountryTypeAndID(ctx context.Context, arg GetActivePCByCountryTypeAndIDParams) (PaymentChannel, error)
	GetActivePaymentChannelsByCountryIDs(ctx context.Context, dollar_1 []int64) ([]GetActivePaymentChannelsByCountryIDsRow, error)
	GetActiveRouteByCountries(ctx context.Context, arg GetActiveRouteByCountriesParams) (Route, error)
	GetAllActiveRouteDestinations(ctx context.Context) ([]GetAllActiveRouteDestinationsRow, error)
	GetAllCountries(ctx context.Context) ([]Country, error)
	GetAllSourceCountries(ctx context.Context) ([]GetAllSourceCountriesRow, error)
	GetAllTransfers(ctx context.Context, arg GetAllTransfersParams) ([]GetAllTransfersRow, error)
	GetAllTransfersCount(ctx context.Context, arg GetAllTransfersCountParams) (int64, error)
	GetCountryByID(ctx context.Context, id int64) (Country, error)
	GetCountryByName(ctx context.Context, name string) (Country, error)
	GetDestCountriesBySrcCountryID(ctx context.Context, sourceCountryID int64) ([]GetDestCountriesBySrcCountryIDRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetPaymentChannelByCountryID(ctx context.Context, countryID int64) (PaymentChannel, error)
	GetPaymentChannelByID(ctx context.Context, id uuid.UUID) (PaymentChannel, error)
	GetTransferByID(ctx context.Context, id uuid.UUID) (GetTransferByIDRow, error)
	GetTransferByReference(ctx context.Context, reference string) (GetTransferByReferenceRow, error)
	GetTransferEventsByTransferID(ctx context.Context, transferID uuid.UUID) ([]TransferEvent, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error)
	SetPaymentProofKey(ctx context.Context, arg SetPaymentProofKeyParams) error
	ToggleRouteActive(ctx context.Context, id uuid.UUID) (Route, error)
	TransitionTransferStatus(ctx context.Context, arg TransitionTransferStatusParams) (int64, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error)
}

var _ Querier = (*Queries)(nil)
