// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
        reference,
        route_id,
        status,
        sender_phone,
        receiving_account_name,
        receiving_mobile_money_number,
        receiving_method,
        receiving_money_network_id,
        receiving_bank_id,
        receiving_bank_account,
        payment_proof_key,
        exchange_rate,
        fee,
        amount_sent,
        amount_received,
        notes,
        expires_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    )
RETURNING id
`

type CreateTransferParams struct {
	Reference                  string
	RouteID                    uuid.UUID
	Status                     TransferStatus
	SenderPhone                string
	ReceivingAccountName       string
	ReceivingMobileMoneyNumber *string
	ReceivingMethod            ReceivingMethods
	ReceivingMoneyNetworkID    pgtype.UUID
	ReceivingBankID            pgtype.UUID
	ReceivingBankAccount       *string
	PaymentProofKey            *string
	ExchangeRate               pgtype.Numeric
	Fee                        pgtype.Numeric
	AmountSent                 pgtype.Numeric
	AmountReceived             pgtype.Numeric
	Notes                      *string
	ExpiresAt                  time.Time
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.Reference,
		arg.RouteID,
		arg.Status,
		arg.SenderPhone,
		arg.ReceivingAccountName,
		arg.ReceivingMobileMoneyNumber,
		arg.ReceivingMethod,
		arg.ReceivingMoneyNetworkID,
		arg.ReceivingBankID,
		arg.ReceivingBankAccount,
		arg.PaymentProofKey,
		arg.ExchangeRate,
		arg.Fee,
		arg.AmountSent,
		arg.AmountReceived,
		arg.Notes,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTransferByReference = `-- name: GetTransferByReference :one
SELECT id, reference, route_id, status, sender_phone, receiving_account_name, receiving_mobile_money_number, receiving_method, receiving_money_network_id, receiving_bank_id, receiving_bank_account, payment_proof_key, exchange_rate, fee, amount_sent, amount_received, notes, expires_at, created_at, updated_at, deleted_at
FROM transfers
WHERE reference = $1
`

func (q *Queries) GetTransferByReference(ctx context.Context, reference string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByReference, reference)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.RouteID,
		&i.Status,
		&i.SenderPhone,
		&i.ReceivingAccountName,
		&i.ReceivingMobileMoneyNumber,
		&i.ReceivingMethod,
		&i.ReceivingMoneyNetworkID,
		&i.ReceivingBankID,
		&i.ReceivingBankAccount,
		&i.PaymentProofKey,
		&i.ExchangeRate,
		&i.Fee,
		&i.AmountSent,
		&i.AmountReceived,
		&i.Notes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
