// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"
)

const getTransferByReference = `-- name: GetTransferByReference :one
SELECT id, reference, route_id, status, sender_name, sender_phone, recipient_name, recipient_phone, receiving_method, network_name, bank_name, recipient_account, send_amount, receive_amount, source_currency, destination_currency, exchange_rate, fee, payment_channel, payment_proof_key, notes, created_at, updated_at, deleted_at
FROM transfers
WHERE reference = $1
`

func (q *Queries) GetTransferByReference(ctx context.Context, reference string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByReference, reference)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.RouteID,
		&i.Status,
		&i.SenderName,
		&i.SenderPhone,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.ReceivingMethod,
		&i.NetworkName,
		&i.BankName,
		&i.RecipientAccount,
		&i.SendAmount,
		&i.ReceiveAmount,
		&i.SourceCurrency,
		&i.DestinationCurrency,
		&i.ExchangeRate,
		&i.Fee,
		&i.PaymentChannel,
		&i.PaymentProofKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
