// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTransferEvent = `-- name: CreateTransferEvent :one
INSERT INTO transfer_events (transfer_id, status, actor, note)
VALUES ($1, $2, $3, $4)
RETURNING id, transfer_id, status, actor, note, created_at
`

type CreateTransferEventParams struct {
	TransferID uuid.UUID
	Status     TransferStatus
	Actor      string
	Note       *string
}

func (q *Queries) CreateTransferEvent(ctx context.Context, arg CreateTransferEventParams) (TransferEvent, error) {
	row := q.db.QueryRow(ctx, createTransferEvent,
		arg.TransferID,
		arg.Status,
		arg.Actor,
		arg.Note,
	)
	var i TransferEvent
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.Status,
		&i.Actor,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getTransferEventsByTransferID = `-- name: GetTransferEventsByTransferID :many
SELECT id, transfer_id, status, actor, note, created_at
FROM transfer_events
WHERE transfer_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTransferEventsByTransferID(ctx context.Context, transferID uuid.UUID) ([]TransferEvent, error) {
	rows, err := q.db.Query(ctx, getTransferEventsByTransferID, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferEvent{}
	for rows.Next() {
		var i TransferEvent
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.Status,
			&i.Actor,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionTransferStatus = `-- name: TransitionTransferStatus :execrows
UPDATE transfers
SET status = $1::transfer_status,
    updated_at = now()
WHERE id = $2
    AND status = $3::transfer_status
    AND deleted_at IS NULL
`

type TransitionTransferStatusParams struct {
	Column1 TransferStatus
	ID      uuid.UUID
	Column3 TransferStatus
}

func (q *Queries) TransitionTransferStatus(ctx context.Context, arg TransitionTransferStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionTransferStatus, arg.Column1, arg.ID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
