// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
        reference,
        route_id,
        status,
        sender_phone,
        receiving_account_name,
        receiving_mobile_money_number,
        receiving_method,
        receiving_money_network_id,
        receiving_bank_id,
        receiving_bank_account,
        payment_proof_key,
        exchange_rate,
        fee,
        amount_sent,
        amount_received,
        notes,
        expires_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    )
RETURNING id
`

type CreateTransferParams struct {
	Reference                  string
	RouteID                    uuid.UUID
	Status                     TransferStatus
	SenderPhone                string
	ReceivingAccountName       string
	ReceivingMobileMoneyNumber *string
	ReceivingMethod            ReceivingMethods
	ReceivingMoneyNetworkID    pgtype.UUID
	ReceivingBankID            pgtype.UUID
	ReceivingBankAccount       *string
	PaymentProofKey            *string
	ExchangeRate               pgtype.Numeric
	Fee                        pgtype.Numeric
	AmountSent                 pgtype.Numeric
	AmountReceived             pgtype.Numeric
	Notes                      *string
	ExpiresAt                  time.Time
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.Reference,
		arg.RouteID,
		arg.Status,
		arg.SenderPhone,
		arg.ReceivingAccountName,
		arg.ReceivingMobileMoneyNumber,
		arg.ReceivingMethod,
		arg.ReceivingMoneyNetworkID,
		arg.ReceivingBankID,
		arg.ReceivingBankAccount,
		arg.PaymentProofKey,
		arg.ExchangeRate,
		arg.Fee,
		arg.AmountSent,
		arg.AmountReceived,
		arg.Notes,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllTransfers = `-- name: GetAllTransfers :many
SELECT t.id, t.reference, t.route_id, t.status, t.sender_phone, t.receiving_account_name, t.receiving_mobile_money_number, t.receiving_method, t.receiving_money_network_id, t.receiving_bank_id, t.receiving_bank_account, t.payment_proof_key, t.exchange_rate, t.fee, t.amount_sent, t.amount_received, t.notes, t.expires_at, t.created_at, t.updated_at, t.deleted_at, t.payment_account_id, t.payment_method, t.payment_account_name, t.payment_account_number, t.payment_channel_name, t.payment_currency_code, t.payment_received_at, t.assurance_sent_at,
    src.id AS source_country_id,
    src.name AS source_country_name,
    src.flag AS source_flag,
    src.currency_symbol AS source_currency_symbol,
    dst.id AS destination_country_id,
    dst.name AS destination_country_name,
    dst.flag AS destination_flag,
    dst.currency_symbol AS destination_currency_symbol,
    network.name AS receiving_network_name,
    bank.name AS receiving_bank_name,
    pc.code AS promo_code,
    pcr.discount_percentage AS promo_discount_percentage
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
    JOIN countries dst ON dst.id = r.destination_country_id
    LEFT JOIN payment_channels network ON network.id = t.receiving_money_network_id
    LEFT JOIN payment_channels bank ON bank.id = t.receiving_bank_id
    LEFT JOIN promo_code_redemptions pcr ON pcr.transfer_id = t.id
    LEFT JOIN promo_codes pc ON pc.id = pcr.promo_code_id
WHERE t.deleted_at IS NULL
    AND t.sender_phone = COALESCE(NULLIF($1::text, ''), t.sender_phone)
    AND COALESCE(t.receiving_mobile_money_number, '') = COALESCE(
        NULLIF($2::text, ''),
        COALESCE(t.receiving_mobile_money_number, '')
    )
    AND t.status = COALESCE(NULLIF($3::text, '')::transfer_status, t.status)
    AND t.reference = COALESCE(NULLIF($4::text, ''), t.reference)
    AND t.route_id = COALESCE(
        NULLIF(
            $5::uuid,
            '00000000-0000-0000-0000-000000000000'::uuid
        ),
        t.route_id
    )
ORDER BY t.created_at DESC
LIMIT $7 OFFSET $6
`

type GetAllTransfersParams struct {
	SenderPhone    string
	RecipientPhone string
	Status         string
	Reference      string
	RouteID        uuid.UUID
	RowOffset      int32
	RowLimit       int32
}

type GetAllTransfersRow struct {
	ID                         uuid.UUID
	Reference                  string
	RouteID                    uuid.UUID
	Status                     TransferStatus
	SenderPhone                string
	ReceivingAccountName       string
	ReceivingMobileMoneyNumber *string
	ReceivingMethod            ReceivingMethods
	ReceivingMoneyNetworkID    pgtype.UUID
	ReceivingBankID            pgtype.UUID
	ReceivingBankAccount       *string
	PaymentProofKey            *string
	ExchangeRate               pgtype.Numeric
	Fee                        pgtype.Numeric
	AmountSent                 pgtype.Numeric
	AmountReceived             pgtype.Numeric
	Notes                      *string
	ExpiresAt                  time.Time
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  pgtype.Timestamptz
	PaymentAccountID           pgtype.UUID
	PaymentMethod              *ReceivingMethods
	PaymentAccountName         *string
	PaymentAccountNumber       *string
	PaymentChannelName         *string
	PaymentCurrencyCode        *string
	PaymentReceivedAt          pgtype.Timestamptz
	AssuranceSentAt            pgtype.Timestamptz
	SourceCountryID            int64
	SourceCountryName          string
	SourceFlag                 string
	SourceCurrencySymbol       string
	DestinationCountryID       int64
	DestinationCountryName     string
	DestinationFlag            string
	DestinationCurrencySymbol  string
	ReceivingNetworkName       *string
	ReceivingBankName          *string
	PromoCode                  *string
	PromoDiscountPercentage    pgtype.Numeric
}

func (q *Queries) GetAllTransfers(ctx context.Context, arg GetAllTransfersParams) ([]GetAllTransfersRow, error) {
	rows, err := q.db.Query(ctx, getAllTransfers,
		arg.SenderPhone,
		arg.RecipientPhone,
		arg.Status,
		arg.Reference,
		arg.RouteID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTransfersRow{}
	for rows.Next() {
		var i GetAllTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.RouteID,
			&i.Status,
			&i.SenderPhone,
			&i.ReceivingAccountName,
			&i.ReceivingMobileMoneyNumber,
			&i.ReceivingMethod,
			&i.ReceivingMoneyNetworkID,
			&i.ReceivingBankID,
			&i.ReceivingBankAccount,
			&i.PaymentProofKey,
			&i.ExchangeRate,
			&i.Fee,
			&i.AmountSent,
			&i.AmountReceived,
			&i.Notes,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PaymentAccountID,
			&i.PaymentMethod,
			&i.PaymentAccountName,
			&i.PaymentAccountNumber,
			&i.PaymentChannelName,
			&i.PaymentCurrencyCode,
			&i.PaymentReceivedAt,
			&i.AssuranceSentAt,
			&i.SourceCountryID,
			&i.SourceCountryName,
			&i.SourceFlag,
			&i.SourceCurrencySymbol,
			&i.DestinationCountryID,
			&i.DestinationCountryName,
			&i.DestinationFlag,
			&i.DestinationCurrencySymbol,
			&i.ReceivingNetworkName,
			&i.ReceivingBankName,
			&i.PromoCode,
			&i.PromoDiscountPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTransfersCount = `-- name: GetAllTransfersCount :one
SELECT COUNT(*)
FROM transfers t
WHERE t.deleted_at IS NULL
    AND t.sender_phone = COALESCE(NULLIF($1::text, ''), t.sender_phone)
    AND COALESCE(t.receiving_mobile_money_number, '') = COALESCE(
        NULLIF($2::text, ''),
        COALESCE(t.receiving_mobile_money_number, '')
    )
    AND t.status = COALESCE(NULLIF($3::text, '')::transfer_status, t.status)
    AND t.reference = COALESCE(NULLIF($4::text, ''), t.reference)
    AND t.route_id = COALESCE(
        NULLIF(
            $5::uuid,
            '00000000-0000-0000-0000-000000000000'::uuid
        ),
        t.route_id
    )
`

type GetAllTransfersCountParams struct {
	SenderPhone    string
	RecipientPhone string
	Status         string
	Reference      string
	RouteID        uuid.UUID
}

func (q *Queries) GetAllTransfersCount(ctx context.Context, arg GetAllTransfersCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAllTransfersCount,
		arg.SenderPhone,
		arg.RecipientPhone,
		arg.Status,
		arg.Reference,
		arg.RouteID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT t.id, t.reference, t.route_id, t.status, t.sender_phone, t.receiving_account_name, t.receiving_mobile_money_number, t.receiving_method, t.receiving_money_network_id, t.receiving_bank_id, t.receiving_bank_account, t.payment_proof_key, t.exchange_rate, t.fee, t.amount_sent, t.amount_received, t.notes, t.expires_at, t.created_at, t.updated_at, t.deleted_at, t.payment_account_id, t.payment_method, t.payment_account_name, t.payment_account_number, t.payment_channel_name, t.payment_currency_code, t.payment_received_at, t.assurance_sent_at,
    src.id AS source_country_id,
    src.name AS source_country_name,
    src.currency_code AS source_currency_code,
    src.currency_symbol AS source_currency_symbol,
    dst.id AS destination_country_id,
    dst.name AS destination_country_name,
    dst.currency_code AS destination_currency_code,
    dst.currency_symbol AS destination_currency_symbol,
    network.name AS receiving_network_name,
    bank.name AS receiving_bank_name
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
    JOIN countries dst ON dst.id = r.destination_country_id
    LEFT JOIN payment_channels network ON network.id = t.receiving_money_network_id
    LEFT JOIN payment_channels bank ON bank.id = t.receiving_bank_id
WHERE t.id = $1
    AND t.deleted_at IS NULL
`

type GetTransferByIDRow struct {
	ID                         uuid.UUID
	Reference                  string
	RouteID                    uuid.UUID
	Status                     TransferStatus
	SenderPhone                string
	ReceivingAccountName       string
	ReceivingMobileMoneyNumber *string
	ReceivingMethod            ReceivingMethods
	ReceivingMoneyNetworkID    pgtype.UUID
	ReceivingBankID            pgtype.UUID
	ReceivingBankAccount       *string
	PaymentProofKey            *string
	ExchangeRate               pgtype.Numeric
	Fee                        pgtype.Numeric
	AmountSent                 pgtype.Numeric
	AmountReceived             pgtype.Numeric
	Notes                      *string
	ExpiresAt                  time.Time
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  pgtype.Timestamptz
	PaymentAccountID           pgtype.UUID
	PaymentMethod              *ReceivingMethods
	PaymentAccountName         *string
	PaymentAccountNumber       *string
	PaymentChannelName         *string
	PaymentCurrencyCode        *string
	PaymentReceivedAt          pgtype.Timestamptz
	AssuranceSentAt            pgtype.Timestamptz
	SourceCountryID            int64
	SourceCountryName          string
	SourceCurrencyCode         string
	SourceCurrencySymbol       string
	DestinationCountryID       int64
	DestinationCountryName     string
	DestinationCurrencyCode    string
	DestinationCurrencySymbol  string
	ReceivingNetworkName       *string
	ReceivingBankName          *string
}

func (q *Queries) GetTransferByID(ctx context.Context, id uuid.UUID) (GetTransferByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransferByID, id)
	var i GetTransferByIDRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.RouteID,
		&i.Status,
		&i.SenderPhone,
		&i.ReceivingAccountName,
		&i.ReceivingMobileMoneyNumber,
		&i.ReceivingMethod,
		&i.ReceivingMoneyNetworkID,
		&i.ReceivingBankID,
		&i.ReceivingBankAccount,
		&i.PaymentProofKey,
		&i.ExchangeRate,
		&i.Fee,
		&i.AmountSent,
		&i.AmountReceived,
		&i.Notes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentAccountID,
		&i.PaymentMethod,
		&i.PaymentAccountName,
		&i.PaymentAccountNumber,
		&i.PaymentChannelName,
		&i.PaymentCurrencyCode,
		&i.PaymentReceivedAt,
		&i.AssuranceSentAt,
		&i.SourceCountryID,
		&i.SourceCountryName,
		&i.SourceCurrencyCode,
		&i.SourceCurrencySymbol,
		&i.DestinationCountryID,
		&i.DestinationCountryName,
		&i.DestinationCurrencyCode,
		&i.DestinationCurrencySymbol,
		&i.ReceivingNetworkName,
		&i.ReceivingBankName,
	)
	return i, err
}

const getTransferByReference = `-- name: GetTransferByReference :one
SELECT t.id, t.reference, t.route_id, t.status, t.sender_phone, t.receiving_account_name, t.receiving_mobile_money_number, t.receiving_method, t.receiving_money_network_id, t.receiving_bank_id, t.receiving_bank_account, t.payment_proof_key, t.exchange_rate, t.fee, t.amount_sent, t.amount_received, t.notes, t.expires_at, t.created_at, t.updated_at, t.deleted_at, t.payment_account_id, t.payment_method, t.payment_account_name, t.payment_account_number, t.payment_channel_name, t.payment_currency_code, t.payment_received_at, t.assurance_sent_at,
    src.id AS source_country_id,
    src.name AS source_country_name,
    src.currency_code AS source_currency_code,
    src.currency_symbol AS source_currency_symbol,
    dst.id AS destination_country_id,
    dst.name AS destination_country_name,
    dst.currency_code AS destination_currency_code,
    dst.currency_symbol AS destination_currency_symbol,
    network.name AS receiving_network_name,
    bank.name AS receiving_bank_name,
    pc.code AS promo_code,
    pcr.discount_percentage AS promo_discount_percentage
FROM transfers t
    JOIN routes r ON r.id = t.route_id
    JOIN countries src ON src.id = r.source_country_id
    JOIN countries dst ON dst.id = r.destination_country_id
    LEFT JOIN payment_channels network ON network.id = t.receiving_money_network_id
    LEFT JOIN payment_channels bank ON bank.id = t.receiving_bank_id
    LEFT JOIN promo_code_redemptions pcr ON pcr.transfer_id = t.id
    LEFT JOIN promo_codes pc ON pc.id = pcr.promo_code_id
WHERE t.reference = $1
    AND t.deleted_at IS NULL
`

type GetTransferByReferenceRow struct {
	ID                         uuid.UUID
	Reference                  string
	RouteID                    uuid.UUID
	Status                     TransferStatus
	SenderPhone                string
	ReceivingAccountName       string
	ReceivingMobileMoneyNumber *string
	ReceivingMethod            ReceivingMethods
	ReceivingMoneyNetworkID    pgtype.UUID
	ReceivingBankID            pgtype.UUID
	ReceivingBankAccount       *string
	PaymentProofKey            *string
	ExchangeRate               pgtype.Numeric
	Fee                        pgtype.Numeric
	AmountSent                 pgtype.Numeric
	AmountReceived             pgtype.Numeric
	Notes                      *string
	ExpiresAt                  time.Time
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  pgtype.Timestamptz
	PaymentAccountID           pgtype.UUID
	PaymentMethod              *ReceivingMethods
	PaymentAccountName         *string
	PaymentAccountNumber       *string
	PaymentChannelName         *string
	PaymentCurrencyCode        *string
	PaymentReceivedAt          pgtype.Timestamptz
	AssuranceSentAt            pgtype.Timestamptz
	SourceCountryID            int64
	SourceCountryName          string
	SourceCurrencyCode         string
	SourceCurrencySymbol       string
	DestinationCountryID       int64
	DestinationCountryName     string
	DestinationCurrencyCode    string
	DestinationCurrencySymbol  string
	ReceivingNetworkName       *string
	ReceivingBankName          *string
	PromoCode                  *string
	PromoDiscountPercentage    pgtype.Numeric
}

func (q *Queries) GetTransferByReference(ctx context.Context, reference string) (GetTransferByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getTransferByReference, reference)
	var i GetTransferByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.RouteID,
		&i.Status,
		&i.SenderPhone,
		&i.ReceivingAccountName,
		&i.ReceivingMobileMoneyNumber,
		&i.ReceivingMethod,
		&i.ReceivingMoneyNetworkID,
		&i.ReceivingBankID,
		&i.ReceivingBankAccount,
		&i.PaymentProofKey,
		&i.ExchangeRate,
		&i.Fee,
		&i.AmountSent,
		&i.AmountReceived,
		&i.Notes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentAccountID,
		&i.PaymentMethod,
		&i.PaymentAccountName,
		&i.PaymentAccountNumber,
		&i.PaymentChannelName,
		&i.PaymentCurrencyCode,
		&i.PaymentReceivedAt,
		&i.AssuranceSentAt,
		&i.SourceCountryID,
		&i.SourceCountryName,
		&i.SourceCurrencyCode,
		&i.SourceCurrencySymbol,
		&i.DestinationCountryID,
		&i.DestinationCountryName,
		&i.DestinationCurrencyCode,
		&i.DestinationCurrencySymbol,
		&i.ReceivingNetworkName,
		&i.ReceivingBankName,
		&i.PromoCode,
		&i.PromoDiscountPercentage,
	)
	return i, err
}

const listTransfersNeedingAssurance = `-- name: ListTransfersNeedingAssurance :many
SELECT id,
    reference,
    sender_phone,
    status,
    amount_sent,
    amount_received,
    payment_received_at,
    created_at
FROM transfers
WHERE deleted_at IS NULL
    AND assurance_sent_at IS NULL
    AND status IN (
        'PAYMENT_RECEIVED',
        'VERIFYING',
        'PROCESSING'
    )
    AND payment_received_at IS NOT NULL
    AND payment_received_at <= $1::timestamptz
ORDER BY payment_received_at ASC
LIMIT $2
`

type ListTransfersNeedingAssuranceParams struct {
	OlderThan time.Time
	RowLimit  int32
}

type ListTransfersNeedingAssuranceRow struct {
	ID                uuid.UUID
	Reference         string
	SenderPhone       string
	Status            TransferStatus
	AmountSent        pgtype.Numeric
	AmountReceived    pgtype.Numeric
	PaymentReceivedAt pgtype.Timestamptz
	CreatedAt         time.Time
}

func (q *Queries) ListTransfersNeedingAssurance(ctx context.Context, arg ListTransfersNeedingAssuranceParams) ([]ListTransfersNeedingAssuranceRow, error) {
	rows, err := q.db.Query(ctx, listTransfersNeedingAssurance, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersNeedingAssuranceRow{}
	for rows.Next() {
		var i ListTransfersNeedingAssuranceRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.SenderPhone,
			&i.Status,
			&i.AmountSent,
			&i.AmountReceived,
			&i.PaymentReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransferAssuranceSent = `-- name: MarkTransferAssuranceSent :execrows
UPDATE transfers
SET assurance_sent_at = now(),
    updated_at = now()
WHERE id = $1
    AND assurance_sent_at IS NULL
    AND deleted_at IS NULL
`

func (q *Queries) MarkTransferAssuranceSent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markTransferAssuranceSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPaymentProofKey = `-- name: SetPaymentProofKey :exec
UPDATE transfers
SET payment_proof_key = $1,
    payment_account_id = $2,
    payment_method = $3,
    payment_account_name = $4,
    payment_account_number = $5,
    payment_channel_name = $6,
    payment_currency_code = $7,
    status = 'PAYMENT_RECEIVED',
    payment_received_at = now(),
    updated_at = now()
WHERE reference = $8
    AND status = 'PENDING_PAYMENT'
    AND deleted_at IS NULL
`

type SetPaymentProofKeyParams struct {
	PaymentProofKey      *string
	PaymentAccountID     pgtype.UUID
	PaymentMethod        *ReceivingMethods
	PaymentAccountName   *string
	PaymentAccountNumber *string
	PaymentChannelName   *string
	PaymentCurrencyCode  *string
	Reference            string
}

func (q *Queries) SetPaymentProofKey(ctx context.Context, arg SetPaymentProofKeyParams) error {
	_, err := q.db.Exec(ctx, setPaymentProofKey,
		arg.PaymentProofKey,
		arg.PaymentAccountID,
		arg.PaymentMethod,
		arg.PaymentAccountName,
		arg.PaymentAccountNumber,
		arg.PaymentChannelName,
		arg.PaymentCurrencyCode,
		arg.Reference,
	)
	return err
}
